language: Go
install:
  - go get -v github.com/spf13/hugo
  - pip install --user awscli
script:
  - hugo version
  - make deploy
branches:
 only:
  - master
env:
  global:
    - secure: FeWWPnH5N+3QwyxYgh+hrMp3g2dDjkvauiSS9wpnEr8CAvTh1FGlIxF/DnN5fPQopVaTNFwgldVGynMb0XrRiAk58eqb/s6HFlXfUK7m8DAeY49b8JXdYl0N1j2HdsOw7e/On9zdGFFfhX2NBnr1yRyDV2VPYrjUo2NDkcWCmnEIQKLy//pwCaQ/LqmtVcXL/+vpxgvokQnqUMlrjTOxHFk+DvcN7DJLEQZK5+GvrrKmvcWe8Xd7Wx+QmHPVRN+6yFu9geo2XtSakkunsfKuRCt3Yeba9O2bC86s2mNc9ekrp0r2dtqJ76Axf7fBxZJCWnR8zU1I1LGCId+2qkBfEyKhoOz9X7/tAdgWxjQA0uOImYNavXoerk+HdNjQg6ImrtTuZxaSBc0HSv6CQ0OVqAewKZF7KGJFiRvpFHxY/Q9gv6zNGpEFrWfGyRzyXXKLVDUVju6/Vwkxrd3ef0GsX7c2brGYjBwdd85Aq44d9aV38gikWLuIAyUsupB+JvvrObPMxXaqnJjJADRcPwJGQJ5TWIZUUcsiS0XdyyqmdRU7OVSrMqwhvYRnKLvioK5fIHi/Vg/Gwov235/efn89PCgli5pbcItAyuqFzXXYgBZ0mktWxkiApuN2BroDuJmBiNNLjw6m6VScbGB5c43lS+yh6RQyfxftZi/dZn8YNHk=
    - secure: CfGtFNirnxi/1PcjP0iFHfxSAXhep67lp44BDKA2ib+JbrHvkt6HW4/31/VriAgzAfAX1k2JAXvdMc+K7qyq3VRUyJHFZEsJ1gtIc0hg5WjA5OJSDcxOtjMU1bR9u1qCPQ7cgrKeH87ahP3mb8goZ78Us2pewW/FRA9TSQP5Iws59NshJ7Mwfd4qNhP3fZJZjDPG5ho/IEIJdRDkifsL+6cN8aPgLDXCuvhocnKUMHG3ZDPxOJuzJMOK6OizcMqUbI9If23Byy3JKhtXKJtQvVanz5gFHPGFlYQJBpLXzq8v+uu7BNrmM/uWMKohyucdASILi16G8Wm6t+QJkp/4NNQ/eS5OUy5FksIh682PX5s2N14kIrVd2/tjNedM3TAVKUgi52aPpsie1Bwoo55lQTaHnj/C6XZi4x4cQQ7WdXRm+SJXoBP7l2N/SfAmouTHJhMjzSoIYVimDLM46yNrWPwp1M4JRtzmeytU+pMqN4ZN6TbqM4Am/lp1oToAX3HE1EHGBj0PFw5Gp+PMrTf/kSXhXumx1utmQ9fvhXXDVBeEGpoxje6JMu7N8g7KgBnvVFo+QuCLkvKw/pDAD3wxVJmF6YeXohFe0fHBEmemPBxC4meot5IOSzbSCurtOx4vdTdPZVEACnGB+mpFTLWijUE3EsnvupyHGToWHSEfeOg=
