language: Go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: QnXqnVknHSrhCOh5Ba/ECG/DgH7r5bqKIQKfRMnQ9xCTVuSC0gXeRdlz11o+ls2w9QMaahEWCZxWA/AMwi/++pePbjYjkpsarDybfarCbTXGrIbdgIWp4FPYlwmm7FBiVH8byZv+UmISUNy7fLSYLVcyRS5CBnFKWkFB5j5BBf7zloy0OvZZgyNmN+Z0ybeFMjPPUPKRYqfDQ0HZ5MqbY7nffETy72awGsTKiTZcYWops2szP4MVElaP9emoSEpYugoPzm9YjOXvW8gLiJwWPgor54Cn//ZoIeDTUg+x6zA0z+SrIIxI22p29krWoY3rUBSvWPf5WmJLL67N8vkr15I8L1l4QTg9zIQKIU/CrrUQjHpSVHWdnil8JcQnyDIFZ96PZ3Oi8X1ubNoowXSU2WTSeYEiHYD1lNhnPOKZJczQajE4g7Na0D0W37jKOVTxXIbv2wuqqiGd65meWwxzoDpkGt+0Rq8LR5kM7TEBA/YGG77Fn3/h9q5kyYot1keVi7djbDHighv5+oZR7Xv5gAXZrnL04AVUEJ6HzqJZpqjtME5WCpEq8MzMs2kGXM0N/gkJkI2FQbgmCQgZs6k8pp4j9NdkkO1QB5+rY7O/C0N4IP4vj0Uyyp/oH8siFlx5BmiP5H7vCE3iFgR3rj7FYtZ7h2xgbcxnnaKcdLIJjsc=
  - secure: ppqann5Wljdm9EWR+qRi29S9fT/DBs2IqnsYxSzBhAGUliLRz+nvdHKyab+MY9jCytyRHR4KOc0cdkizYvBFBUAXY1/KKuroAPWxj4qVJqg2B/wfxAO4U0uCKTA1bg+eXHO8KuShgz/+xOzd1m5DOaiSGlHMYFddvep/Vui4phhc0IH0UUNHpjcod/ttZY3H0H473/Ge7vEI7Fjev5ORye1EpAges2APOsaaPfkDmToDPyaA68DPqJClGz0ufHuHcecS8Xhpq6u0s2wHo6Lp2FA+NeZ6/o+ZERBHqU4oSiG9jtpiJn1f9zjGSxbKKlmnSvmbEJFS0xwGwGeRih2UEIFcl283fzQbB3jIK0tXHyT/DdjbI59cRuYIRPdRC4802b0DWFdinwssLryzoK7+7jyXluZFzXC2QqGdnQC0JeT9t7fIgblDyUneuoxZpEt8QVIrF6wmMBoebJzf4PAJQE5qb7JfNU19cGSrG8G/EYS5mGN3431NTJkoOs3l53oh6RLVVhtXZOTRroKBCIKQuep4/Nd5c/IU9IjNF0UQgWaMlF0kseoXBUprTiXvl0BVbc76wp71E/yBZR+IbObMD4G21C502dggq76DXe+ICPWSoi1BOwqjcsziQUTTbqIGdwOVo6fGVAHJSwwJEgGlQv5TqlNDk8rGdqF6BRpX2IE=
